# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Reproducible Assessment
tagline:          ''
description:      ''
url:              http://reproducibleassessment.com
baseurl:          /

twitter_username:	Dr_Franklund
github_username:	weebeasties
linkedin_username:	cliftonfranklund
google_plus_username:	clifton.franklund

# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Dr. Clifton Franklund'
  url:            http://reproducibleassessment.com/

# Thanks to @mdo for the original theme
# author:
#   name:           'Clifton Franklund'
#   url:            https://twitter.com/Dr_Franklund

paginate:         1

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/weebeasties/weebeasties.github.io

# Algolia
gems:  [algoliasearch-jekyll, jekyll-mermaid]

mermaid:
  src: 'https://github.com/knsv/mermaid/blob/master/src/mermaid.js'

algolia:
  application_id: 'WRD04L05GK'
  index_name: 'reproducibleassessment'
  read_only_api_key: 'a914dbecf47608b85ffca2f2a3cc9aef'
  excluded_files:
    - 404.html
    - index.html
