# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Reproducible Assessment
tagline:          'Using data science to inform the evaluation of student learning'
description:      'Using data science to inform the evaluation of student learning.'
url:              http://reproducibleassessment.com
baseurl:          /
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Dr. Clifton Franklund'
  url:            http://reproducibleassessment.com/
# Thanks to @mdo for the original theme
# author:
#   name:           'Clifton Franklund'
#   url:            https://twitter.com/Dr_Franklund

paginate:         1

# Custom vars
version:          2.1.0

github:
    repo:         https://github.com/weebeasties/weebeasties.github.io

# Algolia
gems:
  - algoliasearch-jekyll

algolia:
  application_id: 'WRD04L05GK'
  index_name: 'reproducibleassessment'
  read_only_api_key: 'a914dbecf47608b85ffca2f2a3cc9aef'
  excluded_files:
    - 404.html
    - index.html
